[package]
authors = ["Cristian Eigel <cristian.eigel@esrlabs.com>"]
edition = "2018"
readme = "README.md"
name = "p004-compass"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.3"
panic-itm = "0.4.0"
stm32f3-discovery = "0.6.0"
micromath = "2.0.0"
cortex-m-rtic = "0.5.9"
