[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F303"
#runner = "arm-none-eabi-gdb -q -x cargoembed.gdb"

rustflags = [
  "-C", "link-arg=-Tlink.x",
]


[build]
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)
